version: "3.1"

networks:
  factory:

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - factory
    container_name: mysql-container-factory
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=factory_app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    networks:
      - factory
    container_name: nginx-factory
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  php-fpm:
    build: docker/php
    networks:
      - factory
    container_name: php-factory
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  node:
    build: docker/node
    container_name: node-factory
    networks:
      - factory
    ports:
      - 3000:3000
    volumes:
      - .:/application
    working_dir: /application
    tty: true
    stdin_open: true
